# Generated by Django 5.1.15 on 2026-02-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
