# Generated by Django 5.1.15 on 2026-02-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=50, help_text='Proficiency 0-100')),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks'), ('databases', 'Databases'), ('devops', 'DevOps'), ('tools', 'Tools'), ('other', 'Other')], default='other', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon class e.g. devicon-python-plain', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
